// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/wealdtech/comptrollerd/services/scheduler"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CancelJob provides a mock function for the type MockService
func (_mock *MockService) CancelJob(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CancelJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_CancelJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelJob'
type MockService_CancelJob_Call struct {
	*mock.Call
}

// CancelJob is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockService_Expecter) CancelJob(ctx interface{}, name interface{}) *MockService_CancelJob_Call {
	return &MockService_CancelJob_Call{Call: _e.mock.On("CancelJob", ctx, name)}
}

func (_c *MockService_CancelJob_Call) Run(run func(ctx context.Context, name string)) *MockService_CancelJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CancelJob_Call) Return(err error) *MockService_CancelJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_CancelJob_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockService_CancelJob_Call {
	_c.Call.Return(run)
	return _c
}

// CancelJobIfExists provides a mock function for the type MockService
func (_mock *MockService) CancelJobIfExists(ctx context.Context, name string) {
	_mock.Called(ctx, name)
	return
}

// MockService_CancelJobIfExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelJobIfExists'
type MockService_CancelJobIfExists_Call struct {
	*mock.Call
}

// CancelJobIfExists is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockService_Expecter) CancelJobIfExists(ctx interface{}, name interface{}) *MockService_CancelJobIfExists_Call {
	return &MockService_CancelJobIfExists_Call{Call: _e.mock.On("CancelJobIfExists", ctx, name)}
}

func (_c *MockService_CancelJobIfExists_Call) Run(run func(ctx context.Context, name string)) *MockService_CancelJobIfExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CancelJobIfExists_Call) Return() *MockService_CancelJobIfExists_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_CancelJobIfExists_Call) RunAndReturn(run func(ctx context.Context, name string)) *MockService_CancelJobIfExists_Call {
	_c.Run(run)
	return _c
}

// CancelJobs provides a mock function for the type MockService
func (_mock *MockService) CancelJobs(ctx context.Context, prefix string) {
	_mock.Called(ctx, prefix)
	return
}

// MockService_CancelJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelJobs'
type MockService_CancelJobs_Call struct {
	*mock.Call
}

// CancelJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
func (_e *MockService_Expecter) CancelJobs(ctx interface{}, prefix interface{}) *MockService_CancelJobs_Call {
	return &MockService_CancelJobs_Call{Call: _e.mock.On("CancelJobs", ctx, prefix)}
}

func (_c *MockService_CancelJobs_Call) Run(run func(ctx context.Context, prefix string)) *MockService_CancelJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CancelJobs_Call) Return() *MockService_CancelJobs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_CancelJobs_Call) RunAndReturn(run func(ctx context.Context, prefix string)) *MockService_CancelJobs_Call {
	_c.Run(run)
	return _c
}

// JobExists provides a mock function for the type MockService
func (_mock *MockService) JobExists(ctx context.Context, name string) bool {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for JobExists")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockService_JobExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JobExists'
type MockService_JobExists_Call struct {
	*mock.Call
}

// JobExists is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockService_Expecter) JobExists(ctx interface{}, name interface{}) *MockService_JobExists_Call {
	return &MockService_JobExists_Call{Call: _e.mock.On("JobExists", ctx, name)}
}

func (_c *MockService_JobExists_Call) Run(run func(ctx context.Context, name string)) *MockService_JobExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_JobExists_Call) Return(b bool) *MockService_JobExists_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockService_JobExists_Call) RunAndReturn(run func(ctx context.Context, name string) bool) *MockService_JobExists_Call {
	_c.Call.Return(run)
	return _c
}

// ListJobs provides a mock function for the type MockService
func (_mock *MockService) ListJobs(ctx context.Context) []string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListJobs")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockService_ListJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListJobs'
type MockService_ListJobs_Call struct {
	*mock.Call
}

// ListJobs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ListJobs(ctx interface{}) *MockService_ListJobs_Call {
	return &MockService_ListJobs_Call{Call: _e.mock.On("ListJobs", ctx)}
}

func (_c *MockService_ListJobs_Call) Run(run func(ctx context.Context)) *MockService_ListJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ListJobs_Call) Return(strings []string) *MockService_ListJobs_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockService_ListJobs_Call) RunAndReturn(run func(ctx context.Context) []string) *MockService_ListJobs_Call {
	_c.Call.Return(run)
	return _c
}

// RunJob provides a mock function for the type MockService
func (_mock *MockService) RunJob(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for RunJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RunJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunJob'
type MockService_RunJob_Call struct {
	*mock.Call
}

// RunJob is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockService_Expecter) RunJob(ctx interface{}, name interface{}) *MockService_RunJob_Call {
	return &MockService_RunJob_Call{Call: _e.mock.On("RunJob", ctx, name)}
}

func (_c *MockService_RunJob_Call) Run(run func(ctx context.Context, name string)) *MockService_RunJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_RunJob_Call) Return(err error) *MockService_RunJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RunJob_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockService_RunJob_Call {
	_c.Call.Return(run)
	return _c
}

// RunJobIfExists provides a mock function for the type MockService
func (_mock *MockService) RunJobIfExists(ctx context.Context, name string) {
	_mock.Called(ctx, name)
	return
}

// MockService_RunJobIfExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunJobIfExists'
type MockService_RunJobIfExists_Call struct {
	*mock.Call
}

// RunJobIfExists is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockService_Expecter) RunJobIfExists(ctx interface{}, name interface{}) *MockService_RunJobIfExists_Call {
	return &MockService_RunJobIfExists_Call{Call: _e.mock.On("RunJobIfExists", ctx, name)}
}

func (_c *MockService_RunJobIfExists_Call) Run(run func(ctx context.Context, name string)) *MockService_RunJobIfExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_RunJobIfExists_Call) Return() *MockService_RunJobIfExists_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_RunJobIfExists_Call) RunAndReturn(run func(ctx context.Context, name string)) *MockService_RunJobIfExists_Call {
	_c.Run(run)
	return _c
}

// ScheduleJob provides a mock function for the type MockService
func (_mock *MockService) ScheduleJob(ctx context.Context, class string, name string, runtime time.Time, job scheduler.JobFunc, data any) error {
	ret := _mock.Called(ctx, class, name, runtime, job, data)

	if len(ret) == 0 {
		panic("no return value specified for ScheduleJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time, scheduler.JobFunc, any) error); ok {
		r0 = returnFunc(ctx, class, name, runtime, job, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_ScheduleJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScheduleJob'
type MockService_ScheduleJob_Call struct {
	*mock.Call
}

// ScheduleJob is a helper method to define mock.On call
//   - ctx context.Context
//   - class string
//   - name string
//   - runtime time.Time
//   - job scheduler.JobFunc
//   - data any
func (_e *MockService_Expecter) ScheduleJob(ctx interface{}, class interface{}, name interface{}, runtime interface{}, job interface{}, data interface{}) *MockService_ScheduleJob_Call {
	return &MockService_ScheduleJob_Call{Call: _e.mock.On("ScheduleJob", ctx, class, name, runtime, job, data)}
}

func (_c *MockService_ScheduleJob_Call) Run(run func(ctx context.Context, class string, name string, runtime time.Time, job scheduler.JobFunc, data any)) *MockService_ScheduleJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 scheduler.JobFunc
		if args[4] != nil {
			arg4 = args[4].(scheduler.JobFunc)
		}
		var arg5 any
		if args[5] != nil {
			arg5 = args[5].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockService_ScheduleJob_Call) Return(err error) *MockService_ScheduleJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_ScheduleJob_Call) RunAndReturn(run func(ctx context.Context, class string, name string, runtime time.Time, job scheduler.JobFunc, data any) error) *MockService_ScheduleJob_Call {
	_c.Call.Return(run)
	return _c
}

// SchedulePeriodicJob provides a mock function for the type MockService
func (_mock *MockService) SchedulePeriodicJob(ctx context.Context, class string, name string, runtime scheduler.RuntimeFunc, runtimeData any, job scheduler.JobFunc, jobData any) error {
	ret := _mock.Called(ctx, class, name, runtime, runtimeData, job, jobData)

	if len(ret) == 0 {
		panic("no return value specified for SchedulePeriodicJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, scheduler.RuntimeFunc, any, scheduler.JobFunc, any) error); ok {
		r0 = returnFunc(ctx, class, name, runtime, runtimeData, job, jobData)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SchedulePeriodicJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SchedulePeriodicJob'
type MockService_SchedulePeriodicJob_Call struct {
	*mock.Call
}

// SchedulePeriodicJob is a helper method to define mock.On call
//   - ctx context.Context
//   - class string
//   - name string
//   - runtime scheduler.RuntimeFunc
//   - runtimeData any
//   - job scheduler.JobFunc
//   - jobData any
func (_e *MockService_Expecter) SchedulePeriodicJob(ctx interface{}, class interface{}, name interface{}, runtime interface{}, runtimeData interface{}, job interface{}, jobData interface{}) *MockService_SchedulePeriodicJob_Call {
	return &MockService_SchedulePeriodicJob_Call{Call: _e.mock.On("SchedulePeriodicJob", ctx, class, name, runtime, runtimeData, job, jobData)}
}

func (_c *MockService_SchedulePeriodicJob_Call) Run(run func(ctx context.Context, class string, name string, runtime scheduler.RuntimeFunc, runtimeData any, job scheduler.JobFunc, jobData any)) *MockService_SchedulePeriodicJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 scheduler.RuntimeFunc
		if args[3] != nil {
			arg3 = args[3].(scheduler.RuntimeFunc)
		}
		var arg4 any
		if args[4] != nil {
			arg4 = args[4].(any)
		}
		var arg5 scheduler.JobFunc
		if args[5] != nil {
			arg5 = args[5].(scheduler.JobFunc)
		}
		var arg6 any
		if args[6] != nil {
			arg6 = args[6].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockService_SchedulePeriodicJob_Call) Return(err error) *MockService_SchedulePeriodicJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SchedulePeriodicJob_Call) RunAndReturn(run func(ctx context.Context, class string, name string, runtime scheduler.RuntimeFunc, runtimeData any, job scheduler.JobFunc, jobData any) error) *MockService_SchedulePeriodicJob_Call {
	_c.Call.Return(run)
	return _c
}
