// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/wealdtech/comptrollerd/services/comptrollerdb"
)

// NewMockReceivedBidsSetter creates a new instance of MockReceivedBidsSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReceivedBidsSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReceivedBidsSetter {
	mock := &MockReceivedBidsSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReceivedBidsSetter is an autogenerated mock type for the ReceivedBidsSetter type
type MockReceivedBidsSetter struct {
	mock.Mock
}

type MockReceivedBidsSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReceivedBidsSetter) EXPECT() *MockReceivedBidsSetter_Expecter {
	return &MockReceivedBidsSetter_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function for the type MockReceivedBidsSetter
func (_mock *MockReceivedBidsSetter) BeginTx(ctx context.Context) (context.Context, context.CancelFunc, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 context.Context
	var r1 context.CancelFunc
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (context.Context, context.CancelFunc, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) context.CancelFunc); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(context.CancelFunc)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockReceivedBidsSetter_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockReceivedBidsSetter_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReceivedBidsSetter_Expecter) BeginTx(ctx interface{}) *MockReceivedBidsSetter_BeginTx_Call {
	return &MockReceivedBidsSetter_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx)}
}

func (_c *MockReceivedBidsSetter_BeginTx_Call) Run(run func(ctx context.Context)) *MockReceivedBidsSetter_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReceivedBidsSetter_BeginTx_Call) Return(context1 context.Context, cancelFunc context.CancelFunc, err error) *MockReceivedBidsSetter_BeginTx_Call {
	_c.Call.Return(context1, cancelFunc, err)
	return _c
}

func (_c *MockReceivedBidsSetter_BeginTx_Call) RunAndReturn(run func(ctx context.Context) (context.Context, context.CancelFunc, error)) *MockReceivedBidsSetter_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// CommitTx provides a mock function for the type MockReceivedBidsSetter
func (_mock *MockReceivedBidsSetter) CommitTx(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CommitTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReceivedBidsSetter_CommitTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitTx'
type MockReceivedBidsSetter_CommitTx_Call struct {
	*mock.Call
}

// CommitTx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReceivedBidsSetter_Expecter) CommitTx(ctx interface{}) *MockReceivedBidsSetter_CommitTx_Call {
	return &MockReceivedBidsSetter_CommitTx_Call{Call: _e.mock.On("CommitTx", ctx)}
}

func (_c *MockReceivedBidsSetter_CommitTx_Call) Run(run func(ctx context.Context)) *MockReceivedBidsSetter_CommitTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReceivedBidsSetter_CommitTx_Call) Return(err error) *MockReceivedBidsSetter_CommitTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReceivedBidsSetter_CommitTx_Call) RunAndReturn(run func(ctx context.Context) error) *MockReceivedBidsSetter_CommitTx_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function for the type MockReceivedBidsSetter
func (_mock *MockReceivedBidsSetter) Metadata(ctx context.Context, key string) ([]byte, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReceivedBidsSetter_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockReceivedBidsSetter_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockReceivedBidsSetter_Expecter) Metadata(ctx interface{}, key interface{}) *MockReceivedBidsSetter_Metadata_Call {
	return &MockReceivedBidsSetter_Metadata_Call{Call: _e.mock.On("Metadata", ctx, key)}
}

func (_c *MockReceivedBidsSetter_Metadata_Call) Run(run func(ctx context.Context, key string)) *MockReceivedBidsSetter_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReceivedBidsSetter_Metadata_Call) Return(bytes []byte, err error) *MockReceivedBidsSetter_Metadata_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockReceivedBidsSetter_Metadata_Call) RunAndReturn(run func(ctx context.Context, key string) ([]byte, error)) *MockReceivedBidsSetter_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// SetMetadata provides a mock function for the type MockReceivedBidsSetter
func (_mock *MockReceivedBidsSetter) SetMetadata(ctx context.Context, key string, value []byte) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for SetMetadata")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReceivedBidsSetter_SetMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMetadata'
type MockReceivedBidsSetter_SetMetadata_Call struct {
	*mock.Call
}

// SetMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value []byte
func (_e *MockReceivedBidsSetter_Expecter) SetMetadata(ctx interface{}, key interface{}, value interface{}) *MockReceivedBidsSetter_SetMetadata_Call {
	return &MockReceivedBidsSetter_SetMetadata_Call{Call: _e.mock.On("SetMetadata", ctx, key, value)}
}

func (_c *MockReceivedBidsSetter_SetMetadata_Call) Run(run func(ctx context.Context, key string, value []byte)) *MockReceivedBidsSetter_SetMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReceivedBidsSetter_SetMetadata_Call) Return(err error) *MockReceivedBidsSetter_SetMetadata_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReceivedBidsSetter_SetMetadata_Call) RunAndReturn(run func(ctx context.Context, key string, value []byte) error) *MockReceivedBidsSetter_SetMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// SetReceivedBid provides a mock function for the type MockReceivedBidsSetter
func (_mock *MockReceivedBidsSetter) SetReceivedBid(ctx context.Context, bid *comptrollerdb.ReceivedBid) error {
	ret := _mock.Called(ctx, bid)

	if len(ret) == 0 {
		panic("no return value specified for SetReceivedBid")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *comptrollerdb.ReceivedBid) error); ok {
		r0 = returnFunc(ctx, bid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReceivedBidsSetter_SetReceivedBid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReceivedBid'
type MockReceivedBidsSetter_SetReceivedBid_Call struct {
	*mock.Call
}

// SetReceivedBid is a helper method to define mock.On call
//   - ctx context.Context
//   - bid *comptrollerdb.ReceivedBid
func (_e *MockReceivedBidsSetter_Expecter) SetReceivedBid(ctx interface{}, bid interface{}) *MockReceivedBidsSetter_SetReceivedBid_Call {
	return &MockReceivedBidsSetter_SetReceivedBid_Call{Call: _e.mock.On("SetReceivedBid", ctx, bid)}
}

func (_c *MockReceivedBidsSetter_SetReceivedBid_Call) Run(run func(ctx context.Context, bid *comptrollerdb.ReceivedBid)) *MockReceivedBidsSetter_SetReceivedBid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *comptrollerdb.ReceivedBid
		if args[1] != nil {
			arg1 = args[1].(*comptrollerdb.ReceivedBid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReceivedBidsSetter_SetReceivedBid_Call) Return(err error) *MockReceivedBidsSetter_SetReceivedBid_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReceivedBidsSetter_SetReceivedBid_Call) RunAndReturn(run func(ctx context.Context, bid *comptrollerdb.ReceivedBid) error) *MockReceivedBidsSetter_SetReceivedBid_Call {
	_c.Call.Return(run)
	return _c
}

// SetReceivedBids provides a mock function for the type MockReceivedBidsSetter
func (_mock *MockReceivedBidsSetter) SetReceivedBids(ctx context.Context, bids []*comptrollerdb.ReceivedBid) error {
	ret := _mock.Called(ctx, bids)

	if len(ret) == 0 {
		panic("no return value specified for SetReceivedBids")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*comptrollerdb.ReceivedBid) error); ok {
		r0 = returnFunc(ctx, bids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReceivedBidsSetter_SetReceivedBids_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReceivedBids'
type MockReceivedBidsSetter_SetReceivedBids_Call struct {
	*mock.Call
}

// SetReceivedBids is a helper method to define mock.On call
//   - ctx context.Context
//   - bids []*comptrollerdb.ReceivedBid
func (_e *MockReceivedBidsSetter_Expecter) SetReceivedBids(ctx interface{}, bids interface{}) *MockReceivedBidsSetter_SetReceivedBids_Call {
	return &MockReceivedBidsSetter_SetReceivedBids_Call{Call: _e.mock.On("SetReceivedBids", ctx, bids)}
}

func (_c *MockReceivedBidsSetter_SetReceivedBids_Call) Run(run func(ctx context.Context, bids []*comptrollerdb.ReceivedBid)) *MockReceivedBidsSetter_SetReceivedBids_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*comptrollerdb.ReceivedBid
		if args[1] != nil {
			arg1 = args[1].([]*comptrollerdb.ReceivedBid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReceivedBidsSetter_SetReceivedBids_Call) Return(err error) *MockReceivedBidsSetter_SetReceivedBids_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReceivedBidsSetter_SetReceivedBids_Call) RunAndReturn(run func(ctx context.Context, bids []*comptrollerdb.ReceivedBid) error) *MockReceivedBidsSetter_SetReceivedBids_Call {
	_c.Call.Return(run)
	return _c
}
