// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/wealdtech/comptrollerd/services/comptrollerdb"
)

// NewMockDeliveredBidsSetter creates a new instance of MockDeliveredBidsSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeliveredBidsSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeliveredBidsSetter {
	mock := &MockDeliveredBidsSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeliveredBidsSetter is an autogenerated mock type for the DeliveredBidsSetter type
type MockDeliveredBidsSetter struct {
	mock.Mock
}

type MockDeliveredBidsSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeliveredBidsSetter) EXPECT() *MockDeliveredBidsSetter_Expecter {
	return &MockDeliveredBidsSetter_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function for the type MockDeliveredBidsSetter
func (_mock *MockDeliveredBidsSetter) BeginTx(ctx context.Context) (context.Context, context.CancelFunc, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 context.Context
	var r1 context.CancelFunc
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (context.Context, context.CancelFunc, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) context.CancelFunc); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(context.CancelFunc)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockDeliveredBidsSetter_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockDeliveredBidsSetter_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDeliveredBidsSetter_Expecter) BeginTx(ctx interface{}) *MockDeliveredBidsSetter_BeginTx_Call {
	return &MockDeliveredBidsSetter_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx)}
}

func (_c *MockDeliveredBidsSetter_BeginTx_Call) Run(run func(ctx context.Context)) *MockDeliveredBidsSetter_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeliveredBidsSetter_BeginTx_Call) Return(context1 context.Context, cancelFunc context.CancelFunc, err error) *MockDeliveredBidsSetter_BeginTx_Call {
	_c.Call.Return(context1, cancelFunc, err)
	return _c
}

func (_c *MockDeliveredBidsSetter_BeginTx_Call) RunAndReturn(run func(ctx context.Context) (context.Context, context.CancelFunc, error)) *MockDeliveredBidsSetter_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// CommitTx provides a mock function for the type MockDeliveredBidsSetter
func (_mock *MockDeliveredBidsSetter) CommitTx(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CommitTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeliveredBidsSetter_CommitTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitTx'
type MockDeliveredBidsSetter_CommitTx_Call struct {
	*mock.Call
}

// CommitTx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDeliveredBidsSetter_Expecter) CommitTx(ctx interface{}) *MockDeliveredBidsSetter_CommitTx_Call {
	return &MockDeliveredBidsSetter_CommitTx_Call{Call: _e.mock.On("CommitTx", ctx)}
}

func (_c *MockDeliveredBidsSetter_CommitTx_Call) Run(run func(ctx context.Context)) *MockDeliveredBidsSetter_CommitTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeliveredBidsSetter_CommitTx_Call) Return(err error) *MockDeliveredBidsSetter_CommitTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeliveredBidsSetter_CommitTx_Call) RunAndReturn(run func(ctx context.Context) error) *MockDeliveredBidsSetter_CommitTx_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function for the type MockDeliveredBidsSetter
func (_mock *MockDeliveredBidsSetter) Metadata(ctx context.Context, key string) ([]byte, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeliveredBidsSetter_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockDeliveredBidsSetter_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockDeliveredBidsSetter_Expecter) Metadata(ctx interface{}, key interface{}) *MockDeliveredBidsSetter_Metadata_Call {
	return &MockDeliveredBidsSetter_Metadata_Call{Call: _e.mock.On("Metadata", ctx, key)}
}

func (_c *MockDeliveredBidsSetter_Metadata_Call) Run(run func(ctx context.Context, key string)) *MockDeliveredBidsSetter_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeliveredBidsSetter_Metadata_Call) Return(bytes []byte, err error) *MockDeliveredBidsSetter_Metadata_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockDeliveredBidsSetter_Metadata_Call) RunAndReturn(run func(ctx context.Context, key string) ([]byte, error)) *MockDeliveredBidsSetter_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// SetDeliveredBid provides a mock function for the type MockDeliveredBidsSetter
func (_mock *MockDeliveredBidsSetter) SetDeliveredBid(ctx context.Context, bid *comptrollerdb.DeliveredBid) error {
	ret := _mock.Called(ctx, bid)

	if len(ret) == 0 {
		panic("no return value specified for SetDeliveredBid")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *comptrollerdb.DeliveredBid) error); ok {
		r0 = returnFunc(ctx, bid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeliveredBidsSetter_SetDeliveredBid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDeliveredBid'
type MockDeliveredBidsSetter_SetDeliveredBid_Call struct {
	*mock.Call
}

// SetDeliveredBid is a helper method to define mock.On call
//   - ctx context.Context
//   - bid *comptrollerdb.DeliveredBid
func (_e *MockDeliveredBidsSetter_Expecter) SetDeliveredBid(ctx interface{}, bid interface{}) *MockDeliveredBidsSetter_SetDeliveredBid_Call {
	return &MockDeliveredBidsSetter_SetDeliveredBid_Call{Call: _e.mock.On("SetDeliveredBid", ctx, bid)}
}

func (_c *MockDeliveredBidsSetter_SetDeliveredBid_Call) Run(run func(ctx context.Context, bid *comptrollerdb.DeliveredBid)) *MockDeliveredBidsSetter_SetDeliveredBid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *comptrollerdb.DeliveredBid
		if args[1] != nil {
			arg1 = args[1].(*comptrollerdb.DeliveredBid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeliveredBidsSetter_SetDeliveredBid_Call) Return(err error) *MockDeliveredBidsSetter_SetDeliveredBid_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeliveredBidsSetter_SetDeliveredBid_Call) RunAndReturn(run func(ctx context.Context, bid *comptrollerdb.DeliveredBid) error) *MockDeliveredBidsSetter_SetDeliveredBid_Call {
	_c.Call.Return(run)
	return _c
}

// SetMetadata provides a mock function for the type MockDeliveredBidsSetter
func (_mock *MockDeliveredBidsSetter) SetMetadata(ctx context.Context, key string, value []byte) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for SetMetadata")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeliveredBidsSetter_SetMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMetadata'
type MockDeliveredBidsSetter_SetMetadata_Call struct {
	*mock.Call
}

// SetMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value []byte
func (_e *MockDeliveredBidsSetter_Expecter) SetMetadata(ctx interface{}, key interface{}, value interface{}) *MockDeliveredBidsSetter_SetMetadata_Call {
	return &MockDeliveredBidsSetter_SetMetadata_Call{Call: _e.mock.On("SetMetadata", ctx, key, value)}
}

func (_c *MockDeliveredBidsSetter_SetMetadata_Call) Run(run func(ctx context.Context, key string, value []byte)) *MockDeliveredBidsSetter_SetMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeliveredBidsSetter_SetMetadata_Call) Return(err error) *MockDeliveredBidsSetter_SetMetadata_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeliveredBidsSetter_SetMetadata_Call) RunAndReturn(run func(ctx context.Context, key string, value []byte) error) *MockDeliveredBidsSetter_SetMetadata_Call {
	_c.Call.Return(run)
	return _c
}
