// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	"github.com/attestantio/go-relay-client/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDeliveredBidTraceProvider creates a new instance of MockDeliveredBidTraceProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeliveredBidTraceProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeliveredBidTraceProvider {
	mock := &MockDeliveredBidTraceProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeliveredBidTraceProvider is an autogenerated mock type for the DeliveredBidTraceProvider type
type MockDeliveredBidTraceProvider struct {
	mock.Mock
}

type MockDeliveredBidTraceProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeliveredBidTraceProvider) EXPECT() *MockDeliveredBidTraceProvider_Expecter {
	return &MockDeliveredBidTraceProvider_Expecter{mock: &_m.Mock}
}

// Address provides a mock function for the type MockDeliveredBidTraceProvider
func (_mock *MockDeliveredBidTraceProvider) Address() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDeliveredBidTraceProvider_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type MockDeliveredBidTraceProvider_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *MockDeliveredBidTraceProvider_Expecter) Address() *MockDeliveredBidTraceProvider_Address_Call {
	return &MockDeliveredBidTraceProvider_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *MockDeliveredBidTraceProvider_Address_Call) Run(run func()) *MockDeliveredBidTraceProvider_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeliveredBidTraceProvider_Address_Call) Return(s string) *MockDeliveredBidTraceProvider_Address_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDeliveredBidTraceProvider_Address_Call) RunAndReturn(run func() string) *MockDeliveredBidTraceProvider_Address_Call {
	_c.Call.Return(run)
	return _c
}

// DeliveredBidTrace provides a mock function for the type MockDeliveredBidTraceProvider
func (_mock *MockDeliveredBidTraceProvider) DeliveredBidTrace(ctx context.Context, slot phase0.Slot) (*v1.BidTrace, error) {
	ret := _mock.Called(ctx, slot)

	if len(ret) == 0 {
		panic("no return value specified for DeliveredBidTrace")
	}

	var r0 *v1.BidTrace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, phase0.Slot) (*v1.BidTrace, error)); ok {
		return returnFunc(ctx, slot)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, phase0.Slot) *v1.BidTrace); ok {
		r0 = returnFunc(ctx, slot)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.BidTrace)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, phase0.Slot) error); ok {
		r1 = returnFunc(ctx, slot)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeliveredBidTraceProvider_DeliveredBidTrace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeliveredBidTrace'
type MockDeliveredBidTraceProvider_DeliveredBidTrace_Call struct {
	*mock.Call
}

// DeliveredBidTrace is a helper method to define mock.On call
//   - ctx context.Context
//   - slot phase0.Slot
func (_e *MockDeliveredBidTraceProvider_Expecter) DeliveredBidTrace(ctx interface{}, slot interface{}) *MockDeliveredBidTraceProvider_DeliveredBidTrace_Call {
	return &MockDeliveredBidTraceProvider_DeliveredBidTrace_Call{Call: _e.mock.On("DeliveredBidTrace", ctx, slot)}
}

func (_c *MockDeliveredBidTraceProvider_DeliveredBidTrace_Call) Run(run func(ctx context.Context, slot phase0.Slot)) *MockDeliveredBidTraceProvider_DeliveredBidTrace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 phase0.Slot
		if args[1] != nil {
			arg1 = args[1].(phase0.Slot)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeliveredBidTraceProvider_DeliveredBidTrace_Call) Return(bidTrace *v1.BidTrace, err error) *MockDeliveredBidTraceProvider_DeliveredBidTrace_Call {
	_c.Call.Return(bidTrace, err)
	return _c
}

func (_c *MockDeliveredBidTraceProvider_DeliveredBidTrace_Call) RunAndReturn(run func(ctx context.Context, slot phase0.Slot) (*v1.BidTrace, error)) *MockDeliveredBidTraceProvider_DeliveredBidTrace_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockDeliveredBidTraceProvider
func (_mock *MockDeliveredBidTraceProvider) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDeliveredBidTraceProvider_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockDeliveredBidTraceProvider_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockDeliveredBidTraceProvider_Expecter) Name() *MockDeliveredBidTraceProvider_Name_Call {
	return &MockDeliveredBidTraceProvider_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockDeliveredBidTraceProvider_Name_Call) Run(run func()) *MockDeliveredBidTraceProvider_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeliveredBidTraceProvider_Name_Call) Return(s string) *MockDeliveredBidTraceProvider_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDeliveredBidTraceProvider_Name_Call) RunAndReturn(run func() string) *MockDeliveredBidTraceProvider_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Pubkey provides a mock function for the type MockDeliveredBidTraceProvider
func (_mock *MockDeliveredBidTraceProvider) Pubkey() *phase0.BLSPubKey {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pubkey")
	}

	var r0 *phase0.BLSPubKey
	if returnFunc, ok := ret.Get(0).(func() *phase0.BLSPubKey); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*phase0.BLSPubKey)
		}
	}
	return r0
}

// MockDeliveredBidTraceProvider_Pubkey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pubkey'
type MockDeliveredBidTraceProvider_Pubkey_Call struct {
	*mock.Call
}

// Pubkey is a helper method to define mock.On call
func (_e *MockDeliveredBidTraceProvider_Expecter) Pubkey() *MockDeliveredBidTraceProvider_Pubkey_Call {
	return &MockDeliveredBidTraceProvider_Pubkey_Call{Call: _e.mock.On("Pubkey")}
}

func (_c *MockDeliveredBidTraceProvider_Pubkey_Call) Run(run func()) *MockDeliveredBidTraceProvider_Pubkey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeliveredBidTraceProvider_Pubkey_Call) Return(bLSPubKey *phase0.BLSPubKey) *MockDeliveredBidTraceProvider_Pubkey_Call {
	_c.Call.Return(bLSPubKey)
	return _c
}

func (_c *MockDeliveredBidTraceProvider_Pubkey_Call) RunAndReturn(run func() *phase0.BLSPubKey) *MockDeliveredBidTraceProvider_Pubkey_Call {
	_c.Call.Return(run)
	return _c
}
