// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	"github.com/attestantio/go-relay-client/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReceivedBidTracesProvider creates a new instance of MockReceivedBidTracesProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReceivedBidTracesProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReceivedBidTracesProvider {
	mock := &MockReceivedBidTracesProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReceivedBidTracesProvider is an autogenerated mock type for the ReceivedBidTracesProvider type
type MockReceivedBidTracesProvider struct {
	mock.Mock
}

type MockReceivedBidTracesProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReceivedBidTracesProvider) EXPECT() *MockReceivedBidTracesProvider_Expecter {
	return &MockReceivedBidTracesProvider_Expecter{mock: &_m.Mock}
}

// Address provides a mock function for the type MockReceivedBidTracesProvider
func (_mock *MockReceivedBidTracesProvider) Address() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockReceivedBidTracesProvider_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type MockReceivedBidTracesProvider_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *MockReceivedBidTracesProvider_Expecter) Address() *MockReceivedBidTracesProvider_Address_Call {
	return &MockReceivedBidTracesProvider_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *MockReceivedBidTracesProvider_Address_Call) Run(run func()) *MockReceivedBidTracesProvider_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReceivedBidTracesProvider_Address_Call) Return(s string) *MockReceivedBidTracesProvider_Address_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockReceivedBidTracesProvider_Address_Call) RunAndReturn(run func() string) *MockReceivedBidTracesProvider_Address_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockReceivedBidTracesProvider
func (_mock *MockReceivedBidTracesProvider) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockReceivedBidTracesProvider_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockReceivedBidTracesProvider_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockReceivedBidTracesProvider_Expecter) Name() *MockReceivedBidTracesProvider_Name_Call {
	return &MockReceivedBidTracesProvider_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockReceivedBidTracesProvider_Name_Call) Run(run func()) *MockReceivedBidTracesProvider_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReceivedBidTracesProvider_Name_Call) Return(s string) *MockReceivedBidTracesProvider_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockReceivedBidTracesProvider_Name_Call) RunAndReturn(run func() string) *MockReceivedBidTracesProvider_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Pubkey provides a mock function for the type MockReceivedBidTracesProvider
func (_mock *MockReceivedBidTracesProvider) Pubkey() *phase0.BLSPubKey {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pubkey")
	}

	var r0 *phase0.BLSPubKey
	if returnFunc, ok := ret.Get(0).(func() *phase0.BLSPubKey); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*phase0.BLSPubKey)
		}
	}
	return r0
}

// MockReceivedBidTracesProvider_Pubkey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pubkey'
type MockReceivedBidTracesProvider_Pubkey_Call struct {
	*mock.Call
}

// Pubkey is a helper method to define mock.On call
func (_e *MockReceivedBidTracesProvider_Expecter) Pubkey() *MockReceivedBidTracesProvider_Pubkey_Call {
	return &MockReceivedBidTracesProvider_Pubkey_Call{Call: _e.mock.On("Pubkey")}
}

func (_c *MockReceivedBidTracesProvider_Pubkey_Call) Run(run func()) *MockReceivedBidTracesProvider_Pubkey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReceivedBidTracesProvider_Pubkey_Call) Return(bLSPubKey *phase0.BLSPubKey) *MockReceivedBidTracesProvider_Pubkey_Call {
	_c.Call.Return(bLSPubKey)
	return _c
}

func (_c *MockReceivedBidTracesProvider_Pubkey_Call) RunAndReturn(run func() *phase0.BLSPubKey) *MockReceivedBidTracesProvider_Pubkey_Call {
	_c.Call.Return(run)
	return _c
}

// ReceivedBidTraces provides a mock function for the type MockReceivedBidTracesProvider
func (_mock *MockReceivedBidTracesProvider) ReceivedBidTraces(ctx context.Context, slot phase0.Slot) ([]*v1.BidTraceWithTimestamp, error) {
	ret := _mock.Called(ctx, slot)

	if len(ret) == 0 {
		panic("no return value specified for ReceivedBidTraces")
	}

	var r0 []*v1.BidTraceWithTimestamp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, phase0.Slot) ([]*v1.BidTraceWithTimestamp, error)); ok {
		return returnFunc(ctx, slot)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, phase0.Slot) []*v1.BidTraceWithTimestamp); ok {
		r0 = returnFunc(ctx, slot)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.BidTraceWithTimestamp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, phase0.Slot) error); ok {
		r1 = returnFunc(ctx, slot)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReceivedBidTracesProvider_ReceivedBidTraces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReceivedBidTraces'
type MockReceivedBidTracesProvider_ReceivedBidTraces_Call struct {
	*mock.Call
}

// ReceivedBidTraces is a helper method to define mock.On call
//   - ctx context.Context
//   - slot phase0.Slot
func (_e *MockReceivedBidTracesProvider_Expecter) ReceivedBidTraces(ctx interface{}, slot interface{}) *MockReceivedBidTracesProvider_ReceivedBidTraces_Call {
	return &MockReceivedBidTracesProvider_ReceivedBidTraces_Call{Call: _e.mock.On("ReceivedBidTraces", ctx, slot)}
}

func (_c *MockReceivedBidTracesProvider_ReceivedBidTraces_Call) Run(run func(ctx context.Context, slot phase0.Slot)) *MockReceivedBidTracesProvider_ReceivedBidTraces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 phase0.Slot
		if args[1] != nil {
			arg1 = args[1].(phase0.Slot)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReceivedBidTracesProvider_ReceivedBidTraces_Call) Return(bidTraceWithTimestamps []*v1.BidTraceWithTimestamp, err error) *MockReceivedBidTracesProvider_ReceivedBidTraces_Call {
	_c.Call.Return(bidTraceWithTimestamps, err)
	return _c
}

func (_c *MockReceivedBidTracesProvider_ReceivedBidTraces_Call) RunAndReturn(run func(ctx context.Context, slot phase0.Slot) ([]*v1.BidTraceWithTimestamp, error)) *MockReceivedBidTracesProvider_ReceivedBidTraces_Call {
	_c.Call.Return(run)
	return _c
}
