// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReceivedHandler creates a new instance of MockReceivedHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReceivedHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReceivedHandler {
	mock := &MockReceivedHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReceivedHandler is an autogenerated mock type for the ReceivedHandler type
type MockReceivedHandler struct {
	mock.Mock
}

type MockReceivedHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReceivedHandler) EXPECT() *MockReceivedHandler_Expecter {
	return &MockReceivedHandler_Expecter{mock: &_m.Mock}
}

// BidsReceived provides a mock function for the type MockReceivedHandler
func (_mock *MockReceivedHandler) BidsReceived(ctx context.Context, slot phase0.Slot) {
	_mock.Called(ctx, slot)
	return
}

// MockReceivedHandler_BidsReceived_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BidsReceived'
type MockReceivedHandler_BidsReceived_Call struct {
	*mock.Call
}

// BidsReceived is a helper method to define mock.On call
//   - ctx context.Context
//   - slot phase0.Slot
func (_e *MockReceivedHandler_Expecter) BidsReceived(ctx interface{}, slot interface{}) *MockReceivedHandler_BidsReceived_Call {
	return &MockReceivedHandler_BidsReceived_Call{Call: _e.mock.On("BidsReceived", ctx, slot)}
}

func (_c *MockReceivedHandler_BidsReceived_Call) Run(run func(ctx context.Context, slot phase0.Slot)) *MockReceivedHandler_BidsReceived_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 phase0.Slot
		if args[1] != nil {
			arg1 = args[1].(phase0.Slot)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReceivedHandler_BidsReceived_Call) Return() *MockReceivedHandler_BidsReceived_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReceivedHandler_BidsReceived_Call) RunAndReturn(run func(ctx context.Context, slot phase0.Slot)) *MockReceivedHandler_BidsReceived_Call {
	_c.Run(run)
	return _c
}
