// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CurrentEpoch provides a mock function for the type MockService
func (_mock *MockService) CurrentEpoch() phase0.Epoch {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CurrentEpoch")
	}

	var r0 phase0.Epoch
	if returnFunc, ok := ret.Get(0).(func() phase0.Epoch); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(phase0.Epoch)
	}
	return r0
}

// MockService_CurrentEpoch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentEpoch'
type MockService_CurrentEpoch_Call struct {
	*mock.Call
}

// CurrentEpoch is a helper method to define mock.On call
func (_e *MockService_Expecter) CurrentEpoch() *MockService_CurrentEpoch_Call {
	return &MockService_CurrentEpoch_Call{Call: _e.mock.On("CurrentEpoch")}
}

func (_c *MockService_CurrentEpoch_Call) Run(run func()) *MockService_CurrentEpoch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_CurrentEpoch_Call) Return(epoch phase0.Epoch) *MockService_CurrentEpoch_Call {
	_c.Call.Return(epoch)
	return _c
}

func (_c *MockService_CurrentEpoch_Call) RunAndReturn(run func() phase0.Epoch) *MockService_CurrentEpoch_Call {
	_c.Call.Return(run)
	return _c
}

// CurrentSlot provides a mock function for the type MockService
func (_mock *MockService) CurrentSlot() phase0.Slot {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CurrentSlot")
	}

	var r0 phase0.Slot
	if returnFunc, ok := ret.Get(0).(func() phase0.Slot); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(phase0.Slot)
	}
	return r0
}

// MockService_CurrentSlot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentSlot'
type MockService_CurrentSlot_Call struct {
	*mock.Call
}

// CurrentSlot is a helper method to define mock.On call
func (_e *MockService_Expecter) CurrentSlot() *MockService_CurrentSlot_Call {
	return &MockService_CurrentSlot_Call{Call: _e.mock.On("CurrentSlot")}
}

func (_c *MockService_CurrentSlot_Call) Run(run func()) *MockService_CurrentSlot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_CurrentSlot_Call) Return(slot phase0.Slot) *MockService_CurrentSlot_Call {
	_c.Call.Return(slot)
	return _c
}

func (_c *MockService_CurrentSlot_Call) RunAndReturn(run func() phase0.Slot) *MockService_CurrentSlot_Call {
	_c.Call.Return(run)
	return _c
}

// FirstSlotOfEpoch provides a mock function for the type MockService
func (_mock *MockService) FirstSlotOfEpoch(epoch phase0.Epoch) phase0.Slot {
	ret := _mock.Called(epoch)

	if len(ret) == 0 {
		panic("no return value specified for FirstSlotOfEpoch")
	}

	var r0 phase0.Slot
	if returnFunc, ok := ret.Get(0).(func(phase0.Epoch) phase0.Slot); ok {
		r0 = returnFunc(epoch)
	} else {
		r0 = ret.Get(0).(phase0.Slot)
	}
	return r0
}

// MockService_FirstSlotOfEpoch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FirstSlotOfEpoch'
type MockService_FirstSlotOfEpoch_Call struct {
	*mock.Call
}

// FirstSlotOfEpoch is a helper method to define mock.On call
//   - epoch phase0.Epoch
func (_e *MockService_Expecter) FirstSlotOfEpoch(epoch interface{}) *MockService_FirstSlotOfEpoch_Call {
	return &MockService_FirstSlotOfEpoch_Call{Call: _e.mock.On("FirstSlotOfEpoch", epoch)}
}

func (_c *MockService_FirstSlotOfEpoch_Call) Run(run func(epoch phase0.Epoch)) *MockService_FirstSlotOfEpoch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 phase0.Epoch
		if args[0] != nil {
			arg0 = args[0].(phase0.Epoch)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_FirstSlotOfEpoch_Call) Return(slot phase0.Slot) *MockService_FirstSlotOfEpoch_Call {
	_c.Call.Return(slot)
	return _c
}

func (_c *MockService_FirstSlotOfEpoch_Call) RunAndReturn(run func(epoch phase0.Epoch) phase0.Slot) *MockService_FirstSlotOfEpoch_Call {
	_c.Call.Return(run)
	return _c
}

// GenesisTime provides a mock function for the type MockService
func (_mock *MockService) GenesisTime() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenesisTime")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockService_GenesisTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenesisTime'
type MockService_GenesisTime_Call struct {
	*mock.Call
}

// GenesisTime is a helper method to define mock.On call
func (_e *MockService_Expecter) GenesisTime() *MockService_GenesisTime_Call {
	return &MockService_GenesisTime_Call{Call: _e.mock.On("GenesisTime")}
}

func (_c *MockService_GenesisTime_Call) Run(run func()) *MockService_GenesisTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GenesisTime_Call) Return(time1 time.Time) *MockService_GenesisTime_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockService_GenesisTime_Call) RunAndReturn(run func() time.Time) *MockService_GenesisTime_Call {
	_c.Call.Return(run)
	return _c
}

// SlotToEpoch provides a mock function for the type MockService
func (_mock *MockService) SlotToEpoch(slot phase0.Slot) phase0.Epoch {
	ret := _mock.Called(slot)

	if len(ret) == 0 {
		panic("no return value specified for SlotToEpoch")
	}

	var r0 phase0.Epoch
	if returnFunc, ok := ret.Get(0).(func(phase0.Slot) phase0.Epoch); ok {
		r0 = returnFunc(slot)
	} else {
		r0 = ret.Get(0).(phase0.Epoch)
	}
	return r0
}

// MockService_SlotToEpoch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SlotToEpoch'
type MockService_SlotToEpoch_Call struct {
	*mock.Call
}

// SlotToEpoch is a helper method to define mock.On call
//   - slot phase0.Slot
func (_e *MockService_Expecter) SlotToEpoch(slot interface{}) *MockService_SlotToEpoch_Call {
	return &MockService_SlotToEpoch_Call{Call: _e.mock.On("SlotToEpoch", slot)}
}

func (_c *MockService_SlotToEpoch_Call) Run(run func(slot phase0.Slot)) *MockService_SlotToEpoch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 phase0.Slot
		if args[0] != nil {
			arg0 = args[0].(phase0.Slot)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_SlotToEpoch_Call) Return(epoch phase0.Epoch) *MockService_SlotToEpoch_Call {
	_c.Call.Return(epoch)
	return _c
}

func (_c *MockService_SlotToEpoch_Call) RunAndReturn(run func(slot phase0.Slot) phase0.Epoch) *MockService_SlotToEpoch_Call {
	_c.Call.Return(run)
	return _c
}

// StartOfEpoch provides a mock function for the type MockService
func (_mock *MockService) StartOfEpoch(epoch phase0.Epoch) time.Time {
	ret := _mock.Called(epoch)

	if len(ret) == 0 {
		panic("no return value specified for StartOfEpoch")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func(phase0.Epoch) time.Time); ok {
		r0 = returnFunc(epoch)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockService_StartOfEpoch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartOfEpoch'
type MockService_StartOfEpoch_Call struct {
	*mock.Call
}

// StartOfEpoch is a helper method to define mock.On call
//   - epoch phase0.Epoch
func (_e *MockService_Expecter) StartOfEpoch(epoch interface{}) *MockService_StartOfEpoch_Call {
	return &MockService_StartOfEpoch_Call{Call: _e.mock.On("StartOfEpoch", epoch)}
}

func (_c *MockService_StartOfEpoch_Call) Run(run func(epoch phase0.Epoch)) *MockService_StartOfEpoch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 phase0.Epoch
		if args[0] != nil {
			arg0 = args[0].(phase0.Epoch)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_StartOfEpoch_Call) Return(time1 time.Time) *MockService_StartOfEpoch_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockService_StartOfEpoch_Call) RunAndReturn(run func(epoch phase0.Epoch) time.Time) *MockService_StartOfEpoch_Call {
	_c.Call.Return(run)
	return _c
}

// StartOfSlot provides a mock function for the type MockService
func (_mock *MockService) StartOfSlot(slot phase0.Slot) time.Time {
	ret := _mock.Called(slot)

	if len(ret) == 0 {
		panic("no return value specified for StartOfSlot")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func(phase0.Slot) time.Time); ok {
		r0 = returnFunc(slot)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockService_StartOfSlot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartOfSlot'
type MockService_StartOfSlot_Call struct {
	*mock.Call
}

// StartOfSlot is a helper method to define mock.On call
//   - slot phase0.Slot
func (_e *MockService_Expecter) StartOfSlot(slot interface{}) *MockService_StartOfSlot_Call {
	return &MockService_StartOfSlot_Call{Call: _e.mock.On("StartOfSlot", slot)}
}

func (_c *MockService_StartOfSlot_Call) Run(run func(slot phase0.Slot)) *MockService_StartOfSlot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 phase0.Slot
		if args[0] != nil {
			arg0 = args[0].(phase0.Slot)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_StartOfSlot_Call) Return(time1 time.Time) *MockService_StartOfSlot_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockService_StartOfSlot_Call) RunAndReturn(run func(slot phase0.Slot) time.Time) *MockService_StartOfSlot_Call {
	_c.Call.Return(run)
	return _c
}

// TimestampToEpoch provides a mock function for the type MockService
func (_mock *MockService) TimestampToEpoch(timestamp time.Time) phase0.Epoch {
	ret := _mock.Called(timestamp)

	if len(ret) == 0 {
		panic("no return value specified for TimestampToEpoch")
	}

	var r0 phase0.Epoch
	if returnFunc, ok := ret.Get(0).(func(time.Time) phase0.Epoch); ok {
		r0 = returnFunc(timestamp)
	} else {
		r0 = ret.Get(0).(phase0.Epoch)
	}
	return r0
}

// MockService_TimestampToEpoch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TimestampToEpoch'
type MockService_TimestampToEpoch_Call struct {
	*mock.Call
}

// TimestampToEpoch is a helper method to define mock.On call
//   - timestamp time.Time
func (_e *MockService_Expecter) TimestampToEpoch(timestamp interface{}) *MockService_TimestampToEpoch_Call {
	return &MockService_TimestampToEpoch_Call{Call: _e.mock.On("TimestampToEpoch", timestamp)}
}

func (_c *MockService_TimestampToEpoch_Call) Run(run func(timestamp time.Time)) *MockService_TimestampToEpoch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_TimestampToEpoch_Call) Return(epoch phase0.Epoch) *MockService_TimestampToEpoch_Call {
	_c.Call.Return(epoch)
	return _c
}

func (_c *MockService_TimestampToEpoch_Call) RunAndReturn(run func(timestamp time.Time) phase0.Epoch) *MockService_TimestampToEpoch_Call {
	_c.Call.Return(run)
	return _c
}

// TimestampToSlot provides a mock function for the type MockService
func (_mock *MockService) TimestampToSlot(timestamp time.Time) phase0.Slot {
	ret := _mock.Called(timestamp)

	if len(ret) == 0 {
		panic("no return value specified for TimestampToSlot")
	}

	var r0 phase0.Slot
	if returnFunc, ok := ret.Get(0).(func(time.Time) phase0.Slot); ok {
		r0 = returnFunc(timestamp)
	} else {
		r0 = ret.Get(0).(phase0.Slot)
	}
	return r0
}

// MockService_TimestampToSlot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TimestampToSlot'
type MockService_TimestampToSlot_Call struct {
	*mock.Call
}

// TimestampToSlot is a helper method to define mock.On call
//   - timestamp time.Time
func (_e *MockService_Expecter) TimestampToSlot(timestamp interface{}) *MockService_TimestampToSlot_Call {
	return &MockService_TimestampToSlot_Call{Call: _e.mock.On("TimestampToSlot", timestamp)}
}

func (_c *MockService_TimestampToSlot_Call) Run(run func(timestamp time.Time)) *MockService_TimestampToSlot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_TimestampToSlot_Call) Return(slot phase0.Slot) *MockService_TimestampToSlot_Call {
	_c.Call.Return(slot)
	return _c
}

func (_c *MockService_TimestampToSlot_Call) RunAndReturn(run func(timestamp time.Time) phase0.Slot) *MockService_TimestampToSlot_Call {
	_c.Call.Return(run)
	return _c
}
